hugo-book: fix hugo v0.139.3 build error
Start building sites …
hugo v0.139.3+extended linux/loong64 BuildDate=unknown

WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.
ERROR deprecated: .Sites.First was deprecated in Hugo v0.127.0 and will be removed in Hugo 0.140.0. Use .Sites.Default instead.
ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.140.0. Use hugo.IsMultilingual instead.
WARN  Page 'HAHAHUGOSHORTCODE15s0HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s1HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s2HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s3HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s4HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s5HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s6HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s7HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s8HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s9HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s10HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s11HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s12HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s13HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s14HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s15HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s16HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s17HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s18HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s19HBHB' not found in 'index'
WARN  Page 'HAHAHUGOSHORTCODE15s20HBHB' not found in 'index'
WARN  Bundle menu mode is deprecated and will be removed
Built in 391 ms
Error: error building site: logged 2 error(s)

Sync themes/hugo-book submodule:
1.Fix deprecation warnings, upgrade to hugo 0.134 (#653):
  e54cf3e6d1c631ed1ea01d758464f2b220f68cb7
2.Remove deprecated bundle/leaf menu type:
  31662538df44f65108ecc71caf48ada5b57071ff

Signed-off-by: Dongyan Qian <dongyan0314@gmail.com>